"""Tests for canonical grammar-segment filters in standard-name search.

Verifies that when physical_base / subject / transformation / … kwargs are
provided, the MCP wrapper forwards them to the canonical backing function and
the backing builds Cypher using property-based matching
(``sn.physical_base = $val``). Property-based filtering is the canonical
approach — it works uniformly for both open-vocabulary segments
(``physical_base``) and closed-vocabulary segments (``subject``,
``component``, …).

All tests are mock-based — no live Neo4j required.
"""

from __future__ import annotations

from unittest.mock import MagicMock, call, patch

import pytest

# ---------------------------------------------------------------------------
# Helpers / fixtures
# ---------------------------------------------------------------------------


def _make_gc(return_value=None):
    """Create a mock GraphClient."""
    gc = MagicMock()
    gc.query = MagicMock(return_value=return_value or [])
    return gc


def _sn_row(name: str = "electron_temperature") -> dict:
    """Minimal StandardName row dict."""
    return {
        "name": name,
        "description": f"Description of {name}",
        "kind": "scalar",
        "unit": "eV",
        "pipeline_status": "drafted",
        "documentation": "",
        "cocos_transformation_type": "",
        "cocos": None,
        "score": 1.0,
    }


# ---------------------------------------------------------------------------
# Test: MCP wrapper routes segment filters to canonical backing
# ---------------------------------------------------------------------------


class TestSegmentFilterRouting:
    """When any segment filter kwarg is set, the backing function receives
    the segment_filters dict."""

    def test_physical_base_filter_passes_to_backing(self) -> None:
        """physical_base kwarg must reach the backing function as segment_filters."""
        gc = _make_gc(return_value=[_sn_row("electron_temperature")])

        with patch(
            "imas_codex.llm.sn_tools._search_sn_backing",
            return_value=[_sn_row("electron_temperature")],
        ) as mock_backing:
            from imas_codex.llm.sn_tools import _search_standard_names

            result = _search_standard_names(
                "temperature", physical_base="temperature", gc=gc
            )

        mock_backing.assert_called_once()
        _, kwargs = mock_backing.call_args
        assert kwargs["segment_filters"] == {"physical_base": "temperature"}
        assert "electron_temperature" in result

    def test_subject_filter_passes_to_backing(self) -> None:
        """subject kwarg must reach the backing function as segment_filters."""
        gc = _make_gc(return_value=[])

        with patch(
            "imas_codex.llm.sn_tools._search_sn_backing",
            return_value=[],
        ) as mock_backing:
            from imas_codex.llm.sn_tools import _search_standard_names

            _search_standard_names("electron", subject="electron", gc=gc)

        mock_backing.assert_called_once()
        _, kwargs = mock_backing.call_args
        assert kwargs["segment_filters"] == {"subject": "electron"}

    def test_no_filter_calls_backing_without_segment_filters(self) -> None:
        """With no segment filters, backing is called with segment_filters=None."""
        gc = _make_gc(return_value=[])

        with patch(
            "imas_codex.llm.sn_tools._search_sn_backing",
            return_value=[],
        ) as mock_backing:
            from imas_codex.llm.sn_tools import _search_standard_names

            _search_standard_names("temperature", gc=gc)

        mock_backing.assert_called_once()
        _, kwargs = mock_backing.call_args
        assert kwargs["segment_filters"] is None


# ---------------------------------------------------------------------------
# Test: canonical _segment_filter_search builds correct Cypher
# ---------------------------------------------------------------------------


class TestSegmentFilterCypher:
    """Verify the Cypher generated by the canonical backing helper."""

    def test_single_filter_cypher_contains_property_condition(self) -> None:
        """physical_base filter → Cypher must use sn.physical_base property match."""
        gc = _make_gc()
        from imas_codex.standard_names.search import _segment_filter_search

        _segment_filter_search(
            gc,
            "temperature",
            20,
            {"physical_base": "temperature"},
            None,
            None,
            None,
            None,
        )

        assert gc.query.called
        cypher = gc.query.call_args[0][0]
        assert "sn.physical_base" in cypher

    def test_two_filter_cypher_contains_both_property_conditions(self) -> None:
        """physical_base + subject → both property conditions in Cypher."""
        gc = _make_gc()
        from imas_codex.standard_names.search import _segment_filter_search

        _segment_filter_search(
            gc,
            "electron temperature",
            20,
            {"physical_base": "temperature", "subject": "electron"},
            None,
            None,
            None,
            None,
        )

        cypher = gc.query.call_args[0][0]
        assert "sn.physical_base" in cypher
        assert "sn.subject" in cypher

    def test_filter_param_value_passed_to_query(self) -> None:
        """Token value must be passed as a Cypher parameter, not inlined."""
        gc = _make_gc()
        from imas_codex.standard_names.search import _segment_filter_search

        _segment_filter_search(
            gc,
            "temperature",
            10,
            {"physical_base": "temperature"},
            None,
            None,
            None,
            None,
        )

        kwargs = gc.query.call_args[1]
        # One of the kwargs should be the token value
        assert "temperature" in kwargs.values()

    def test_unknown_segment_skipped_gracefully(self) -> None:
        """An unrecognised segment key must not raise and must return empty."""
        gc = _make_gc()
        from imas_codex.standard_names.search import _segment_filter_search

        result = _segment_filter_search(
            gc,
            "anything",
            5,
            {"not_a_real_segment": "foo"},
            None,
            None,
            None,
            None,
        )

        assert result == []
        assert gc.query.called
        cypher = gc.query.call_args[0][0]
        assert "WHERE true" in cypher

    def test_k_limit_passed_to_query(self) -> None:
        """k parameter must be forwarded as the LIMIT value."""
        gc = _make_gc()
        from imas_codex.standard_names.search import _segment_filter_search

        _segment_filter_search(
            gc,
            "x",
            7,
            {"subject": "electron"},
            None,
            None,
            None,
            None,
        )

        kwargs = gc.query.call_args[1]
        assert kwargs.get("k") == 7

    def test_physics_domain_is_pushed_into_cypher(self) -> None:
        """physics_domain filtering belongs to the backing query, not the wrapper."""
        gc = _make_gc()
        from imas_codex.standard_names.search import _segment_filter_search

        _segment_filter_search(
            gc,
            "",
            7,
            {"subject": "electron"},
            None,
            None,
            None,
            "transport",
        )

        cypher = gc.query.call_args[0][0]
        kwargs = gc.query.call_args[1]
        assert "source_domains" in cypher
        assert kwargs.get("physics_domain") == "transport"


# ---------------------------------------------------------------------------
# Test: end-to-end single-filter — single segment filter returns only matches
# ---------------------------------------------------------------------------


class TestSegmentFilterEndToEnd:
    """Integration-style tests over _search_standard_names with mock backing."""

    def test_single_segment_filter_returns_matching_rows(self) -> None:
        """physical_base='temperature' should return temperature-based names only."""
        matching_row = _sn_row("electron_temperature")
        gc = _make_gc()

        with patch(
            "imas_codex.llm.sn_tools._search_sn_backing",
            return_value=[matching_row],
        ):
            from imas_codex.llm.sn_tools import _search_standard_names

            result = _search_standard_names(
                "temperature", physical_base="temperature", gc=gc
            )

        assert "electron_temperature" in result
        assert "plasma_current" not in result

    def test_two_segment_and_filter(self) -> None:
        """physical_base + subject must both appear in the segment_filters dict."""
        gc = _make_gc(return_value=[])

        with patch(
            "imas_codex.llm.sn_tools._search_sn_backing",
            return_value=[],
        ) as mock_backing:
            from imas_codex.llm.sn_tools import _search_standard_names

            _search_standard_names(
                "electron temperature",
                physical_base="temperature",
                subject="electron",
                gc=gc,
            )

        _, kwargs = mock_backing.call_args
        assert kwargs["segment_filters"] == {
            "physical_base": "temperature",
            "subject": "electron",
        }

    def test_no_match_returns_empty_report(self) -> None:
        """When backing returns no rows, result must indicate no matches found."""
        gc = _make_gc()

        with patch(
            "imas_codex.llm.sn_tools._search_sn_backing",
            return_value=[],
        ):
            from imas_codex.llm.sn_tools import _search_standard_names

            result = _search_standard_names(
                "nothing", physical_base="nonexistent_token", gc=gc
            )

        assert "No standard names found" in result

    def test_fallback_when_no_typed_edges_in_graph(self) -> None:
        """When backing returns empty, segment filter returns empty — no error."""
        gc = _make_gc(return_value=[])

        with patch(
            "imas_codex.llm.sn_tools._search_sn_backing",
            return_value=[],
        ):
            from imas_codex.llm.sn_tools import _search_standard_names

            result = _search_standard_names(
                "temperature", physical_base="temperature", gc=gc
            )

        # Must not raise; must return a well-formed "no results" report
        assert isinstance(result, str)
        assert "No standard names found" in result


# ---------------------------------------------------------------------------
# Test: MCP server schema exposes segment filter params
# ---------------------------------------------------------------------------


class TestMCPServerSegmentParams:
    """Verify search_standard_names tool in server.py accepts segment params."""

    def test_search_sn_tool_accepts_physical_base(self) -> None:
        """search_standard_names tool must accept physical_base and other segment kwargs."""
        import inspect

        from imas_codex.llm.server import AgentsServer

        server = AgentsServer(dd_only=False, include_standard_names=True)

        # Find the registered search_standard_names tool function via MCP components
        tool_fn = None
        for key, component in server.mcp._local_provider._components.items():
            if key.startswith("tool:") and "search_standard_names" in key:
                tool_fn = component.fn
                break

        assert tool_fn is not None, "search_standard_names tool not registered"
        sig = inspect.signature(tool_fn)
        params = sig.parameters
        assert "physical_base" in params, "physical_base param must be in MCP tool"
        assert "subject" in params, "subject param must be in MCP tool"
        assert "transformation" in params, "transformation param must be in MCP tool"
        assert "component" in params, "component param must be in MCP tool"
        assert "coordinate" in params, "coordinate param must be in MCP tool"
        assert "process" in params, "process param must be in MCP tool"
        assert "position" in params, "position param must be in MCP tool"
        assert "region" in params, "region param must be in MCP tool"
        assert "device" in params, "device param must be in MCP tool"
        assert "geometric_base" in params, "geometric_base param must be in MCP tool"
